// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBY9RZZAZ5jAy3IRVkDYDChvQS1AWqztc',
    appId: '1:232607319645:web:640efa983323c38114afb4',
    messagingSenderId: '232607319645',
    projectId: 'uber---rayhan',
    authDomain: 'uber---rayhan.firebaseapp.com',
    storageBucket: 'uber---rayhan.appspot.com',
    measurementId: 'G-ZE12V2KKR5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzGK5Atb_qLPPBbR5oxfTaHLPp-hkmGzY',
    appId: '1:232607319645:android:30944d10c864c07414afb4',
    messagingSenderId: '232607319645',
    projectId: 'uber---rayhan',
    storageBucket: 'uber---rayhan.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCncAbIWUt2jkBeyqFNTr9Od70GqfoFsiw',
    appId: '1:232607319645:ios:091dc45d9786714b14afb4',
    messagingSenderId: '232607319645',
    projectId: 'uber---rayhan',
    storageBucket: 'uber---rayhan.appspot.com',
    iosClientId: '232607319645-mqmqkb36mtk34imesa7bumivv96pcdvo.apps.googleusercontent.com',
    iosBundleId: 'com.example.uber',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCncAbIWUt2jkBeyqFNTr9Od70GqfoFsiw',
    appId: '1:232607319645:ios:091dc45d9786714b14afb4',
    messagingSenderId: '232607319645',
    projectId: 'uber---rayhan',
    storageBucket: 'uber---rayhan.appspot.com',
    iosClientId: '232607319645-mqmqkb36mtk34imesa7bumivv96pcdvo.apps.googleusercontent.com',
    iosBundleId: 'com.example.uber',
  );
}
